<a href="https://colab.research.google.com/github/Sjing2/SJ_practice/blob/master/crawl_test_1/crawl_test_1/spiders/24_Community_based_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comminity C 생성
- 00_word.csv에서 label_result.csv의 user_id와 매칭되는 inner_id로 변환하기
- 예시. 강원도

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
labeled_df = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Label/label_result.csv')
labeled_df['region'].value_counts()

수도    1283
경상     837
충청     319
강원     224
전라     129
Name: region, dtype: int64

In [ ]:
labeled_df['gw'] = labeled_df['region'].isin(['강원'])
labeled_df['cc'] = labeled_df['region'].isin(['충청'])
labeled_df['jl'] = labeled_df['region'].isin(['전라'])
labeled_df['sd'] = labeled_df['region'].isin(['수도'])
labeled_df['gs'] = labeled_df['region'].isin(['경상'])

In [ ]:
labeled_df

     region     insta_id     gw     cc     jl     sd     gs
0        수도      0.21_se  False  False  False   True  False
1        수도    00_msssss  False  False  False   True  False
2        수도      00_wlwl  False  False  False   True  False
3        충청    01.su_jin  False   True  False  False  False
4        충청   0104ayoung  False   True  False  False  False
...     ...          ...    ...    ...    ...    ...    ...
2787     수도   zumba.hara  False  False  False   True  False
2788     수도  zumba_honey  False  False  False   True  False
2789     수도   zusainbolt  False  False  False   True  False
2790     수도   zzang__mat  False  False  False   True  False
2791     수도     zzin1069  False  False  False   True  False

[2792 rows x 7 columns]

In [ ]:
gw_index = labeled_df.index[labeled_df['gw'] == True].tolist()
cc_index = labeled_df.index[labeled_df['cc'] == True].tolist()
jl_index = labeled_df.index[labeled_df['jl'] == True].tolist()
sd_index = labeled_df.index[labeled_df['sd'] == True].tolist()
gs_index = labeled_df.index[labeled_df['gs'] == True].tolist()

In [ ]:
print(len(gw_index), len(cc_index), len(jl_index), len(sd_index), len(gs_index))

224 319 129 1283 837

In [ ]:
labeled_ls = labeled_df['insta_id'].tolist()

In [ ]:
# 지역별 labeling된 user_id 리스트 생성
def extract_id(index, labeled_ls):
    id_ls = []
    for i, v in enumerate(labeled_ls):
        for j in index:
            if i == j:
                id_ls.append(v)
    return id_ls

In [ ]:
gw_userid = extract_id(gw_index, labeled_ls)
cc_userid = extract_id(cc_index, labeled_ls)
jl_userid = extract_id(jl_index, labeled_ls)
sd_userid = extract_id(sd_index, labeled_ls)
gs_userid = extract_id(gs_index, labeled_ls)

In [ ]:
print(gw_userid)

['_06_._.15', 'ashinnn29', 'b_ing_bing', 'choijihyenim', 'corexwavebjj', 'daeuny02', 'drago_n74', 'eom_han74', 'frangsoa11', 'gyeongho6496', 'hehe._.rinn', 'hhhn_0000', 'j_jiwo_o', 'jiyoon_only_one', 'kitarr_man', 'leejunging', 'love_jo_12', 'lshak56', 'm220rookie_driver', 'official__doyeol', 'ours2film', 'sien_401', 'so_oyomii_', 'strong_0915', 'sumneey', 'yeong_0l', 'by__heesoo', 'kang_kang_min', '1997_april_seventeen', '1__person.stone', '2019_dah', '4_8h_ny', '51sn_reset', '71m0jun', '97_dong_geun', '97_j_chan', '97_kr_lsy', '9_9eunjung', '9ooin', '___jeonhye', '__yooneunbin', '_ba_kaerim', '_jju_dec', '_kyoungk', '_woong__96', 'ae_lalalala', 'ahyoungyeah', 'archipro_um', 'azrael2828', 'bamgol.official', 'bk_bin', 'bond2bnd', 'byeongdeok_e', 'c.c_in_plan', 'c__gyu__castle', 'cangmin1384', 'chaedorable', 'cheoooooooool', 'ckm_316', 'd5ngm2n2', 'da_hi98_', 'dabinn_im', 'daehan.lee.5', 'dal._.bom_official', 'ddyeon2', 'diswknd', 'doki.__.97', 'dong_baesun', 'e__s00_', 'eom_giyongi_8.2', 'funandfam', 'g_won00', 'gina_hyunji', 'ging_gaeng_i', 'gr___lee', 'gracepraise_7', 'gyeongchan310', 'h.s_93', 'h.sang_hyuk', 'h_yungmin', 'hallymjob', 'hanbitt38', 'hang2ing', 'hanji_festival', 'heani_j', 'hj_innnnnn', 'hkin1234', 'ho_yao7o5', 'hoguma_a', 'holy_hyeok', 'hongking0325', 'hs_980103', 'hunrism', 'hwangs_deli', 'hyeok._.e', 'hyeonseo7', 'hyuner__y', 'in_seong_boom9', 'ison_cake', 'itislims', 'j._.jinnn', 'jaew.o', 'jamesjoung', 'jayslivingsoul', 'jh_kim_honey', 'ji_hwan.97', 'jiin__ah', 'jin_syong', 'jinny4wish_law', 'jiu_joa', 'jjinwoo_yu', 'jjj2n_', 'jjj_y0ung', 'jjjkys124', 'jo_my97', 'jobpd.lee', 'jong_se_0311', 'jungeunly', 'jungmin.chai', 'junsseob', 'juuuun.w00', 'jy.04.28', 'jys_love95', 'keybeom00', 'kim_spasm', 'king_hm_97', 'kongdu_', 'kwan_65', 'kwon037', 'leeming_961024', 'lgh.1999', 'lifelong.hallym', 'lucius_mg', 'maengmool_', 'morrie_yong', 'mylife_hongju', 'nayoung__jin', 'ocb1107', 'oo__okay', 'ozoombo__', 'park__win', 'pha_ros', 'present_choi', 'pretty78381', 'ptw0404', 'rang_9_', 'rime_jina', 'rlawo_0', 's2_emin_13', 's_sujiniya', 'salt.sc', 'sangwons95', 'see_un12', 'seo_hyeon_c', 'serim_ing', 'seungsu1', 'sh_96.12.21', 'sheuuuvv', 'shinwogml', 'sk_s2_us', 'solokk660', 'srlaqudwns', 'ssoo_0924', 'ssun_glory_', 'sudukoo', 'suhyun__kim', 'suzy_vividly', 'swoosh______', 'sy_kxx', 'taehyeon_x', 'taeil.yoon.790', 'tiarachuncheon', 'tingmin_sing', 'uij00', 'uws1209', 'vpdlssla', 'whole_bubble', 'why_soopsubin', 'wise_lee_09.04', 'wjdtjdgns__', 'xx___hwan', 'ye.o_o', 'ye1_ol', 'ye_one_two_three', 'yeah._.pury', 'yeahyeony', 'yennny_zhen', 'yeoungjoo0914', 'yerimstg', 'yoo_ra_97', 'youdo_yololife', 'yourimss', 'yuji_daily', 'yujin___0419', 'yun_ssong_', 'yunhoi93', 'yyunsang', 'zzingho88', 'zzong2_world', 'k__euihwan', 'ks_.j', 'kyumi0919', 'nasaeii__ii', 'sm.sy.mc', 'taegi__kim', 'won_kyun12', 'k__euihwan', 'ks_.j', 'kyumi0919', 'nasaeii__ii', 'sm.sy.mc', 'taegi__kim', 'won_kyun12', '_in_ne', 'aquadaeho', 'ccomjissamji', 'cho_eun_ik', 'clickcho83', 'damri_wom_mom', 'eunkyoung9704', 'jeongwan78', 'jokkbal', 'kwh740505', 'morish02']

### 모든 지역 word.csv합치기
- 모든 지역의 user_id와 inner_id를 추출하기 위함

In [ ]:
df1 = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/3. delete_businessword/gw_word.csv')
df2 = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/3. delete_businessword/cc_word.csv')
df3 = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/3. delete_businessword/gs_word.csv')
df4 = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/3. delete_businessword/jl_word.csv')
df5 = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/3. delete_businessword/sd_word.csv')

In [ ]:
result = df1.append(df2)
result = result.append(df3)
result = result.append(df4)
result = result.append(df5)

In [ ]:
result.reset_index(inplace=True)

In [ ]:
df = result.drop('index', axis=1)
df # 전체 지역 합친 거

          insta_id  ...    shortcode
0           leeclo  ...          NaN
1           leeclo  ...          NaN
2           leeclo  ...          NaN
3           leeclo  ...          NaN
4           leeclo  ...          NaN
...            ...  ...          ...
114008  asdf0_4_03  ...  CEoadlMn9jO
114009  asdf0_4_03  ...  CEnj9VJHmEs
114010  asdf0_4_03  ...  CElWMgPneEn
114011  asdf0_4_03  ...  CEk4O3MnCL4
114012  asdf0_4_03  ...  CEkftsNH2nx

[114013 rows x 14 columns]

In [ ]:
id_df = df[['insta_id', 'inner_id']]
id_df

          insta_id     inner_id
0           leeclo       831796
1           leeclo       831796
2           leeclo       831796
3           leeclo       831796
4           leeclo       831796
...            ...          ...
114008  asdf0_4_03  41116185668
114009  asdf0_4_03  41116185668
114010  asdf0_4_03  41116185668
114011  asdf0_4_03  41116185668
114012  asdf0_4_03  41116185668

[114013 rows x 2 columns]

### 각 지역별 labeling된 userid를 innerid로 변환하기
- {insta_id : inner_id} 사전생성 후, 매칭되는 userid를 innerid로 변환

In [ ]:
# 전체 지역의 {insta_id : inner_id} 사전생성

def create_id_dic(id_df):
    id_dic = {}
    for insta, inner in zip(id_df['insta_id'], id_df['inner_id']):
        if insta in id_dic.keys() or inner in id_dic.values():
            pass
        else:
            id_dic[insta] = inner
    return id_dic

In [ ]:
all_id_dic = create_id_dic(id_df)
len(all_id_dic)

5589

In [ ]:
all_id_dic

{'leeclo': 831796,
 'niya78': 954459,
 'mintyfish': 1102783,
 'e.hyobbooo': 2780865,
 'evo4gwk': 2781035,
 '0woo': 4309433,
 'younghpark': 5025491,
 'onair_mv': 6865364,
 'fourntwo': 8856447,
 'js4531': 10914187,
 'kkkk_8dio': 11514768,
 'znius': 17804826,
 'itssamlew': 21974230,
 'schach': 22120334,
 'seungsu1': 22269590,
 'jon_joven': 23073881,
 'hyunwoo.rhee': 30479892,
 'warholer': 42580319,
 's_seulllllll': 44667331,
 'jeongyunsun': 45193647,
 'esther.noh': 47861360,
 'chacharming._.304': 48341509,
 'cheong_b': 49410040,
 'chuppachu': 55972894,
 'kjy.0713': 189729667,
 'limhakzin': 209054650,
 'theeggplant__': 215473187,
 'chunok_': 223317742,
 'i77__k': 226362517,
 'spicysalty_corn': 231487500,
 'choyeoni._.i': 237166990,
 'myeong_geun_choi': 247370627,
 'da_hyeon_0324': 255551076,
 'han_d2o': 257021438,
 'navyoxo': 258916762,
 'evilevahong': 261560888,
 'moonk90': 270672119,
 'smigolrum': 283362054,
 'shamanismpop': 285023131,
 'ji.oneandonly': 285664669,
 '2_h1_': 287739443,
 'h_h_ss_': 289960178,
 'eyes_0.612': 294738251,
 'rekki96_jo': 295947101,
 'i_am__min': 306275875,
 'seanyoon81': 307075954,
 'gina_hyunji': 307065634,
 'hannah_04_12': 307115550,
 'yooeveryday': 308443679,
 'young_1.9.9.6': 321756833,
 'j._.jinnn': 322294327,
 'compatible_kim': 331447673,
 'jiyunmi': 332451561,
 'hayanggrace': 362219101,
 '59596gnee': 366961312,
 'c_young97': 369086796,
 'glorymufc_ella': 391711388,
 '__yooneunbin': 415271707,
 'yellow.jin': 423355873,
 'seongeonofficial': 424029447,
 '12_21jjh': 436424783,
 'jungyo_yu': 438150713,
 'sinyeong.q': 450393296,
 'sion_blee': 453620078,
 'volumearth': 467117198,
 'yun____a': 467631601,
 'v0.0v21': 471609828,
 'cheonil1659': 474993154,
 'h.jjoy': 483753170,
 'fresh._.kyung': 486014706,
 'hodolchoi': 487662129,
 'rightsky_1101': 487677118,
 'sarfguy': 499736971,
 'pickupwind': 504442303,
 'rambozzing': 508092961,
 'lifeman21': 525152015,
 'tak.0.2': 534243931,
 'kbbeom': 537614368,
 'hoiiyya': 542559861,
 'jeeheem': 545155488,
 'yi.seu1': 545503070,
 'uio104': 546095503,
 'leeeunsoul': 548517863,
 'subin___li__a': 549911147,
 'hyogenie__': 550196371,
 'shining0507': 550258033,
 'oo_hhyi_': 554625689,
 'ar1015choi': 564714654,
 'dobby_free_ddong': 566579499,
 'sghyun_ee': 568430384,
 'lunalux_bpk_': 571266810,
 'honeysol_64': 572823227,
 'u_jin2h': 580291740,
 'o115_511o': 588070494,
 'm_md32': 600773373,
 '1xol2': 610006881,
 'jolacute_jy': 610344700,
 '_jiyoonnn': 613051289,
 'jyl9709': 618476777,
 'dabinn_im': 618637905,
 'taekwondist_igor': 628586120,
 '_dajeongs2': 632415981,
 'ajwpower': 636229247,
 'og_1104': 637768802,
 'chacha_j1n': 643807032,
 'winter.pandaamakeup': 645321314,
 'uujin_k': 645849888,
 'fullofeun': 646992769,
 'andonggeun': 652348336,
 'byeun11': 653290225,
 'yeoungjoo0914': 656683993,
 'ging_gaeng_i': 657345069,
 'yeeeommm': 660410106,
 'hye._.won_2': 660876059,
 'tyeeeon': 661630805,
 'jiu_joa': 661954653,
 'choishinw00': 664432828,
 'kwonohroro': 665381547,
 'jungeunly': 670358826,
 'bbin__': 681471156,
 'gyeongrable': 681602241,
 'kwonyujin_': 682687251,
 'heemalaya': 685560017,
 '__hyunsutagram__': 703539877,
 'gemmxa': 704978498,
 'pl_._41': 717877633,
 'dayomi96': 721283725,
 'imcheongki': 726654683,
 'g.woooni': 737038534,
 'a_niz_': 790229745,
 'ramg.lee': 790690988,
 'bond2bnd': 799312277,
 'easy_y0ung': 870921635,
 'jeongcc': 877521259,
 'holy_hyeok': 925980797,
 'uijeong2': 932119679,
 'darinee2': 972203697,
 'a_a_hyojeong_': 969430461,
 '0dawan': 964948202,
 'jaeyong_cheon': 987050631,
 'redappledie': 987144381,
 'yeonvely28': 992467744,
 'mxxdoo_': 999707505,
 'yu._.jinni': 999825525,
 'jeeensong': 1016311643,
 'inye98': 1029612752,
 'adsong3': 1040595190,
 'shinehwii': 1048458461,
 'som__._.j': 1056240933,
 'ssun_glory_': 1067720731,
 'hanyeein': 1070621875,
 '85000_gram': 1072315070,
 'jjjinly___': 1072562313,
 '292513joyul': 1077055821,
 'hamnhk': 1101481949,
 'minttomeok0_0': 1103779995,
 'i_m__right': 1111254096,
 'hyemini_e_': 1114703631,
 'yuuun__is': 1119766683,
 '26_ddc': 1119996446,
 'ch___0i': 1124204217,
 'hyeong_gyu9_9': 1124425532,
 'jjammm2': 1124456632,
 '1012funny': 1127118757,
 'his_raroo': 1133203308,
 'pixxa_k': 1136938542,
 'dbgk__': 1145417124,
 'mye0nghun': 1148494783,
 'kor_min': 1155780517,
 'lyj3422': 1172410718,
 'yet_ong2': 1192728533,
 'wook._.ee': 1194544970,
 '_o802_': 1202464372,
 'ob_minvely': 1206566432,
 'ggaeggae': 1209542389,
 '__jina90': 1215358705,
 'yeah._.pury': 1216600715,
 '1hyeoooon': 1217917807,
 '_shy0en_': 1222918539,
 '12.15_je': 1225158705,
 'chony0__0': 1231132853,
 'seooooong_': 1234930132,
 'jaehye0k__': 1248240592,
 'azrael2828': 1238717881,
 'heani_j': 1248751428,
 'jun2stagram': 1250959360,
 'hmin_everything': 1251120094,
 'leeeeeeedg': 1253726621,
 'jh_kim_honey': 1256213041,
 'bomin_l': 1258524973,
 'river_mountain_jeon': 1268755120,
 'naeun0825': 1271863017,
 's.byeok_air': 1272572374,
 'chae_wonnnn': 1277064333,
 'sb22n': 1277225117,
 'youngbinko73': 1277584771,
 'moon_seong_s': 1278898281,
 'n__oung': 1280831549,
 '1007__hj': 1288113708,
 '1110_yn_': 1288457147,
 'ye_zies': 1289662597,
 'zzen._.s': 1300628528,
 'gimmick_seong': 1300909476,
 'h_mmju3': 1313333798,
 'sunghyen_95': 1314328193,
 'seol_hs88': 1314968527,
 'c1shiwons': 1315147241,
 'ddyeon2': 1317437356,
 '_y_n1._': 1319154254,
 'rnjsskdo': 1319842647,
 'chazero__': 1320972198,
 'ryung_v._.v': 1321264924,
 'ss_song96': 1323045252,
 'az_sooa_b': 1324088385,
 '97_j_chan': 1327197734,
 'jn__xu': 1328422470,
 'dyd_rb': 1334646546,
 'pyo_0813_': 1335911612,
 'phb_98': 1336919469,
 'nyeong_chan_s': 1338850592,
 'minzy_p_': 1339780098,
 'binpyo': 1340070132,
 'hkin1234': 1345057329,
 'hyunsunc': 1347488045,
 'jayslivingsoul': 1352362747,
 'e__luna_crecient': 1354314943,
 'li_lool_in': 1358904672,
 'hang2ing': 1360302673,
 'jun_ph': 1360650874,
 'da_eun1103': 1364976167,
 'jeongmo_o': 1366460280,
 'lla_young': 1371926467,
 'yrzzz_z': 1373674464,
 'pini_nn': 1373732884,
 'hyuner__y': 1375398469,
 'cerisier121': 1379923035,
 'k___minnnnn': 1386136140,
 '1_hand': 1388667271,
 'jojonghajo': 1390389848,
 'jo_seungjae': 1392036749,
 'soo.__.ss': 1393201755,
 'ocb1107': 1394511555,
 'jhtrbl': 1394819796,
 '_ba_kaerim': 1395772823,
 '_mi__ju_': 1395830361,
 'suhyun__kim': 1398124862,
 '_yeol__e': 1400464010,
 '_dongh2': 1401864077,
 'hyonchori': 1403518761,
 '93__561': 1404755382,
 '_daseul2': 1407014859,
 'y0on_j_': 1410565902,
 'jyr0510': 1410884747,
 'jaej.97': 1411361624,
 'jy___1127': 1412178477,
 'pkyurr': 1414538044,
 'tree_03_09': 1414617431,
 'silverzero96': 1415493477,
 'yoo_ra_97': 1417127022,
 'sy_kxx': 1418404159,
 'sangwons95': 1419077527,
 '1997_april_seventeen': 1419363253,
 'd_yeon_24': 1419488819,
 'akasilo': 1420836174,
 'chisa_nk': 1422660427,
 'jay__hyuk': 1423987003,
 'ozeannnnn': 1424268232,
 '7k.yho_wot': 1424790416,
 'jinoo.kim': 1425181444,
 'chang_kim_': 1426117611,
 'vjpulse_works': 1428737286,
 '97_kr_lsy': 1429768186,
 'choihyeongjin_choihyeongjin': 1429816843,
 'my2kr': 1431419893,
 'seoung._.0608': 1431609872,
 'thisissein': 1432420854,
 'happy_min86': 1432660406,
 'ha_bnz': 1432637849,
 'hyunil.k': 1433348991,
 'joonsang1996': 1433387606,
 'w_jo0on': 1434701935,
 'do_hyeoniiiii': 1434750039,
 'noah_k_98': 1434974912,
 'yeeramm__o0o': 1435846408,
 'seungchez': 1437093730,
 'kyocci_n': 1439206303,
 '_e.asy_': 1440377373,
 'hongzuyan': 1441337896,
 'ssseong_yong': 1441341797,
 'opus.22_': 1441980851,
 'im_joo0': 1442165982,
 'd5ngm2n2': 1442444765,
 'genie_k_p': 1443410586,
 'hy0_jin_': 1443503168,
 'd._y99': 1443677987,
 'ssu_wari': 1445425540,
 'justdeanowattup': 1445539435,
 'p_b_woong': 1447027016,
 'ddooong_h': 1447494594,
 'tlsdyrnt': 1449330602,
 'bhw_bymi': 1450107846,
 'up_h16': 1451867600,
 'claeo_99': 1453120657,
 'teeth_he': 1453707521,
 'gune_bbu': 1454318401,
 'glendale_23': 1455489026,
 'hwaayyeon': 1456237725,
 'soooo_ji': 1457501308,
 'pizzazmatteng': 1460255687,
 'bbang.up': 1460628879,
 'hynbblee': 1464668400,
 'min_sung93': 1465336045,
 'kim_jooooo': 1467449040,
 'simon_jiwoo': 1467771522,
 'bro_wook_s': 1467917703,
 'kinstar23': 1469208110,
 'h.s_93': 1469344997,
 'happyounyear': 1469939130,
 'keeeehun__': 1472058111,
 'lovely_yj_eee': 1472588891,
 'jeehye_vv': 1473691669,
 '98_jun_5': 1473770301,
 'changbaek.yoo': 1475485182,
 'spain_keun': 1477846475,
 'rlawo_0': 1477990603,
 'jungmin.chai': 1482884719,
 'sy_9762': 1483451683,
 'seungbinim': 1484134631,
 'bin_seop': 1484584050,
 'dongg_ukk': 1490182734,
 'yennny_zhen': 1490300839,
 'galjima_o': 1491145383,
 'sun_j_23': 1492118997,
 'minjae_jeon_': 1493886996,
 'whitemusk0809': 1494976489,
 'd5h2_': 1495000470,
 'j.yeop23': 1495568297,
 'oo_oll8': 1495683006,
 'metti0602': 1495849347,
 'tttaeyyyeon': 1495986641,
 'ssseull__': 1499461059,
 'limjindoll': 1501024154,
 'do_jin_myung': 1501248895,
 's2._.ryeong': 1501727684,
 'sharp_d': 1502459948,
 'kim_sinjong_nn': 1503889483,
 'lucius_mg': 1510091412,
 's_ummmer_': 1513148557,
 'seung_yeon_joa': 1513334037,
 'min_yong_eom': 1515756290,
 'uij00': 1517723316,
 'st_one_6': 1519741261,
 'glo_fo': 1519772124,
 'choie19': 1521754521,
 '92hyunjin_jo': 1523009401,
 'e.sun__': 1523683288,
 'royal_loop__': 1523537067,
 'hyu_nin': 1525160628,
 'mingvely710': 1526019738,
 'taehyeon_x': 1526778026,
 'parkjjang1': 1527381350,
 'chi_.huahua': 1528332950,
 'of_yun_': 1529264630,
 'bong__i': 1529993775,
 'komey_hojun0915': 1530257143,
 'tatunyongh': 1533262882,
 '_eunvlly_': 1535415000,
 'might_yo': 1535355580,
 'sss_rok_': 1535643706,
 '62000g': 1538215175,
 'kxxngji_0': 1538362515,
 'sungmoo_j': 1538372502,
 'moon_g25': 1538719688,
 '3h1nu': 1539615257,
 'ru_han.e': 1540030502,
 'garam.c': 1543613033,
 'wise_lee_09.04': 1545343201,
 'hyeon9mak': 1546445910,
 'pygmy_97': 1546703667,
 'sooni_9': 1547221567,
 'eunnnji94': 1547571763,
 'f_minologue': 1548347951,
 'hui__.shin': 1548709478,
 'ho._.1_06': 1548880302,
 'playd.inc': 1550595852,
 'taeyeonnnnnnnnnnnnn': 1551148216,
 'archipro_um': 1552091689,
 'byunguk1': 1552543260,
 'kinggyujin_': 1553137873,
 'lee.ocg': 1555860554,
 'g_won00': 1556145844,
 'sabefire': 1558106092,
 'y_seongmiin': 1558182190,
 'yong_ss_': 1560411753,
 'wook_hwi': 1560268814,
 '97_dong_geun': 1560546355,
 '1997.yyh': 1561907052,
 'doyun______': 1563003750,
 'seohyun.99.03.16': 1563341775,
 'ziiii_su': 1571223806,
 'junky.26': 1575700556,
 'seo_hyeon_c': 1584465443,
 'goody_eun': 1587339763,
 'ssssohyun_p': 1587848759,
 'py.cat_o3o': 1589751926,
 'nate_with_iji': 1590025428,
 '_seong_h.j_': 1592740272,
 'a_riel_98': 1594011875,
 '3rd_js': 1595354931,
 'hwang.hsh': 1598097519,
 'taeil.yoon.790': 1598751942,
 'wonmaker': 1598876474,
 'minxxsuj': 1598517326,
 'sho9o9_': 1599791836,
 'juwon.k_': 1600008148,
 'curieux_xx': 1602202606,
 'be11nine': 1603146593,
 'alle.tti': 1605682253,
 'kongseokwon': 1606419884,
 'gmcmxmak_951103': 1606421949,
 'zonggunii': 1606688853,
 's.04_26': 1608289212,
 'blackhole_kim': 1608385258,
 'noweed_420': 1616158931,
 'lagcomkin': 1617134842,
 'j2onghj': 1621678119,
 'dldmsrla': 1626866334,
 'phw1369': 1627392430,
 'seong.__.hwan': 1627582945,
 'jun_jun__98': 1631538375,
 'enana_423': 1631984890,
 'z_oonon': 1633983197,
 'rang_9_': 1635151007,
 'win_six': 1639315291,
 'live_with_gratitudes': 1645149565,
 'a_man_who_cooks_music': 1645430035,
 'minnnji_': 1647266041,
 'lgh.1999': 1648214524,
 'he_j02': 1648451427,
 'ch_yji': 1648425089,
 'videong05': 1649516532,
 'skudio_i': 1650827020,
 'dd.ddwest': 1657285090,
 'sang6199': 1658919563,
 'wkdwnrhd': 1664011538,
 'ganghyunnnn': 1666748069,
 'yoon_hong_sik': 1668692769,
 'p93.03.11': 1671529423,
 'b_seongwook': 1673531207,
 'choi.haeum_': 1673596609,
 'young_my054': 1674637665,
 'woo_6_kk': 1674837364,
 'joo_h_j_9628': 1675198226,
 'maru180_official': 1677307661,
 'a_dmire': 1679881744,
 'ahn._.gr': 1681933297,
 'u.u_sun_': 1683918475,
 'qmtanashati': 1687007100,
 'seraphina0505': 1688932107,
 'min0elvin_': 1691423147,
 'grincesssun': 1694348718,
 'eahcnimooy': 1696262091,
 'jaew.o': 1696565165,
 'heejuicy_': 1698693828,
 'w._.jm': 1698686813,
 'beezzang__': 1699218738,
 'jang_chef97': 1699222984,
 'loo_hyun_': 1700270414,
 'oo7oo.28': 1704350794,
 'owinhun_e': 1706940947,
 'mib_geonmin_kim': 1707608088,
 'shaykwondo': 1707341234,
 '2h_ming': 1709319884,
 'alexjiun3': 1710255239,
 'cucumber_52': 1712232047,
 'kuny_p': 1713773717,
 'deokkyu.lee': 1717665738,
 'y.dalm_217': 1721127779,
 'greentea_icecreme': 1727877890,
 '1_27_cw': 1728516254,
 '2hong79': 1729492197,
 'subiiiibbb': 1730250212,
 'yerimstg': 1734302259,
 'yeopbi__': 1736679862,
 'jasung0124': 1738650247,
 'hongking0325': 1743068932,
 'leeming_961024': 1744300397,
 'hongbikang': 1744689365,
 'tie_gip': 1744780300,
 'eoneo.wwa': 1746861650,
 'taeynk': 1747475497,
 'jjjkys124': 1747976321,
 'yyunsang': 1750369590,
 'mch911471': 1751495837,
 'chaedorable': 1754653290,
 'gangjunmo': 1755440007,
 'junne_0127': 1760210576,
 'eunkyung0209': 1760437336,
 'jo_my97': 1761911203,
 'mean_gyun': 1762879202,
 '_chantel_goodley__igu_': 1768608400,
 'ji_soo._.0712': 1768926973,
 '__dasol__': 1770911818,
 'dssc0521': 1773493550,
 'yongje_eum': 1774375421,
 'jinwoo92_': 1781251432,
 'choi__seunghun': 1787164870,
 '_oiab_8': 1789369208,
 '9ooin': 1791031958,
 'omang_xx': 1795515349,
 'iamgarame': 1797640900,
 'keepit_vibes': 1804777776,
 'igotthewholeworld': 1808347278,
 'hoguma_a': 1808052904,
 'hee_wani': 1810803856,
 'kongdu_': 1810914273,
 'oo__okay': 1811555632,
 'juunhwanp': 1812238448,
 'leejae__h': 1813188714,
 'geekid_': 1813537564,
 'cjaeeh': 1814417920,
 'li_cai_run': 1815582781,
 'su.hye0n2': 1815741735,
 'dayyy.2': 1816064078,
 'n_jungeol': 1817439940,
 'k_jeongung': 1818359318,
 'tingmin_sing': 1822415348,
 'j_h_rhee': 1824662125,
 '97.hyeji': 1900351672,
 'j___weon': 1905661309,
 'hyesoo_ryu': 1904981312,
 '96_jin_yong': 1906376416,
 'subbb_98_': 1910996624,
 'about_jacy': 1913279872,
 'maa_ssang': 1910654455,
 'yooosep_kim': 1917285417,
 'sohehik': 1922484773,
 'hyemin_ini': 1922995266,
 'warni___2105': 1923802447,
 'hana.97_': 1926984507,
 'jinseon_17': 1927348238,
 'tiranous00': 1928569113,
 'kanesh_sh01': 1928443312,
 'b__huyn97': 1932831419,
 'jeonggg__97': 1933762435,
 'lky0534': 1939373457,
 'seung.j_k': 1939574282,
 'two_circle_stone': 1940031157,
 'jin._.oh': 1943228239,
 'bgtagd': 1944844123,
 'jisun_park_092': 1946094869,
 'wxxzuni_': 1949707692,
 'yun_ssong_': 1954314828,
 'jiny._.0': 1956116998,
 'ldh_97': 1958859433,
 '1.58_22': 1960619551,
 'heo___ssi': 1962274969,
 '98m__o': 1961913687,
 'iamherjun_': 1965688129,
 '99lsw': 1968844118,
 'j__hyeon_j': 1969257775,
 'kkl5727': 1963523347,
 'kim_ssseongmin': 1971902654,
 '98_yong1': 1972745231,
 'present_choi': 1973023831,
 '422_ho': 1973886288,
 'rime_jina': 1974563553,
 'juyeon__oo': 1975718646,
 'hyeon122793': 1976041568,
 'ch_anxiety': 1979492407,
 's_syena': 1981538342,
 'jungeunlee_lee': 1984602579,
 'eom_giyongi_8.2': 1985513212,
 '9_9eunjung': 1991897650,
 'hongramgram_': 1993256234,
 'vpdlssla': 2000882874,
 'hyowon1111': 2008697805,
 'ae_lalalala': 2007661220,
 'y0un__ju_': 2008713148,
 'chang_of_lee': 2008884836,
 'min_gyu_h': 2010910478,
 'hyun__june': 2012042800,
 'kkk__hong': 2014821882,
 'ol6zlvzl': 2017249031,
 'bigdaddystudio': 2020810905,
 'chz.pepper': 2023825943,
 'naaah_n': 2031028437,
 'psoyun94': 2037389813,
 'climb_star_09pv': 2039146363,
 'to_jisuuuuu': 2040685663,
 'kim__ji_won_': 2042440480,
 'j_sollll': 2043076882,
 'cokejini_': 2045314239,
 'yoo._.nn': 2048904844,
 'syunf7752': 2049609987,
 'sudukoo': 2050048905,
 'kunghun97': 2056099998,
 'shakg_g8': 2058466100,
 '2y._.h2': 2059204097,
 'dh_9.6': 2061787641,
 'm__chil.t': 2065697652,
 '0_eunn': 2065901438,
 'iam_heez': 2069672433,
 'jeong_ryeol_cjr': 2072352622,
 'pretty_sooh': 2073230415,
 'jamx2_in': 2073827716,
 'ted__jung': 2077541869,
 'm_hak_100': 2078339968,
 'sj_sj__': 2083158458,
 'xaeik': 2086261317,
 'ch__hyyun': 2088277753,
 '1.won': 2092243745,
 'sa_mu_el_____': 2102433105,
 'jaenam__': 2102816376,
 'reli__sh': 2104809509,
 'eun._._y': 2105827730,
 'yeon_dreamer._.tuna': 2113809935,
 'jang.jjoon': 2114929672,
 'king_hm_97': 2116988570,
 'taegi_ahn': 2117646020,
 'slowcd': 2119352304,
 'jji_yui': 2120541451,
 '97_jeon_0507': 2121667377,
 'kwj08': 2123621589,
 'sang_uniii': 2125814752,
 'lhg0807': 2128675381,
 'hongxi8017': 2130096967,
 's_mansk': 2130517377,
 'andy.jh.yi': 2133426449,
 '96seon_mok': 2136649236,
 'seungrn': 2136703624,
 'h.s91c': 2137482790,
 'y2ll._.02': 2138808144,
 'kang_0529': 2138476550,
 'iam__ssong': 2144347711,
 'chanhwa_n': 2157469336,
 'sung_jz': 2162835093,
 'yunie9191': 2170345272,
 'byungha619': 2172508433,
 'hello_dada1': 2177301153,
 'p.djoooongg__': 2177351167,
 'happycampus': 2178154694,
 'joo.queen': 2186577756,
 'jin_syong': 2190001875,
 'dolceelen': 2196566352,
 'hoyaa_': 2197664418,
 'ch._.yb_0901': 2197803764,
 'dong_baesun': 2201823069,
 '_nnno12': 2205994648,
 'youdo_yololife': 2208753161,
 'sseol_mellia': 2210821978,
 'changk0': 2211197308,
 '_lovuri': 2215938252,
 'jeongin_park97': 2225478645,
 '98dong_mee': 2228727729,
 'ozoombo__': 2228860695,
 'park__win': 2230039178,
 'junmin_coe': 2231407861,
 'cksam_109': 2232792412,
 'lim_whatiam': 2233326615,
 'darong._.2': 2239731659,
 'jae_mi96': 2242494113,
 'xxsojeongxx': 2243342994,
 's.ga_ri': 2243529273,
 'vomyangov': 2250345218,
 'chanwon.b': 2250789349,
 'shinseongjoo__': 2253809133,
 'seonghy98': 2256879811,
 'yeonsuzz': 2257417063,
 'iam_justmeee': 2262895948,
 'hyeonseo7': 2265034252,
 'dkssyd_b': 2265518574,
 'soom_nij': 2269546494,
 'yu__uri': 2270705100,
 'ryusehyeon0515': 2271171747,
 'yado_dodo': 2277140507,
 'candid_20': 2279222228,
 '51sn_reset': 2280337373,
 'youn9eunk': 2280577667,
 'gusrb0609': 2284543178,
 'ye1_ol': 2284987931,
 'easy._.hoony': 2285180731,
 'hyunsoo0628': 2287062483,
 'witty._.s_h': 2291114625,
 'hanbin0104': 2291354412,
 'ptw0404': 2293777026,
 's.e.katy': 2294770353,
 'se_se_hee': 2294634862,
 'simugin02': 2297024273,
 'k_assia_98': 2300366982,
 'minj6186': 2302272889,
 'j0oooonyfairy': 2302485651,
 'jnbrand_co': 2307137332,
 'nagermm': 2307435271,
 'kmdnghyun_dabo': 2308710881,
 'seongbucoe': 2317806816,
 'na_myong': 2321249876,
 'a.doleful.ditty': 2323007330,
 'do_dri320': 2323434941,
 'srlaqudwns': 2324695276,
 'ss_jinn.0': 2324336269,
 'aberyoung': 2327020522,
 'koownugeel': 2327770103,
 'si_yeon_oo': 2330102570,
 'lion_ssong2': 2331807946,
 'taeunn': 2333222922,
 'millggu': 2332095068,
 'hee.s.hee': 2333320131,
 'j_h__22': 2335433681,
 'yu_d_s_2': 2336380559,
 'qkqnxoddl98': 2341916482,
 'ss2on_': 2341702681,
 '4_8h_ny': 2342679107,
 'woosik_0126': 2343028038,
 'c__gyu__castle': 2348816352,
 'woopidopi': 2351987237,
 'you_andme.1230': 2352522260,
 'chal__nee': 2359287529,
 'g_hyeon_ez': 2360850408,
 '96_hong': 2360952394,
 'geu_jeo_bit': 2364555675,
 'louie_225': 2398728079,
 'green_0711': 2429401795,
 'sung_kwan_yoon': 2431226239,
 'ssangbok': 2462405686,
 'color.young': 2503072167,
 'hwaaaaaaaaan': 2521694491,
 'u.gun9': 2526419565,
 'yujeongful_09': 2532482049,
 'cangmin1384': 2535488750,
 'hoonie_y': 2541254832,
 'truecopy_mika': 2540741302,
 'yujeong_0518': 2575103574,
 'k______y3': 2575334334,
 'gill_sh00': 2610762942,
 'danielstagram_0119': 2667213159,
 'qhdgns4166': 2668380928,
 'bk_bin': 2668996658,
 'zl.o_o.k': 2677396972,
 'e__s00_': 2692599714,
 'b.u_uuk': 2692618686,
 'hoedon_kwon': 2701794206,
 '100.__.sh': 2708020979,
 'hyein4998': 2714516119,
 'ccuing2': 2719972672,
 'cheda_1222': 2720409774,
 'mo_sun_2': 2746017685,
 '2jweon2': 2770421324,
 'honeyjin98': 2869917203,
 'robin04280': 2870340396,
 'jjae_0_': 2889819373,
 '820_nam': 2900191745,
 'hyunhotti_': 2909478552,
 'yang926_1': 2919379608,
 'maengmool_': 2926531458,
 'shin_ho7': 2935409287,
 'give__bottle': 2944371385,
 'afterlosing': 2945707812,
 'seungeon___96': 2945790184,
 'sa_anghooni': 2950693429,
 'dongyun7477': 2949558239,
 'diswknd': 2977981819,
 'hyosunnnnnn_._': 2981299526,

In [ ]:
# 각 지역별 labeling된 userid를 innerid로 변환하기

def user_to_inner(all_id_dic, userid_ls):
    innerid = []
    for (key, elem) in all_id_dic.items():
        for i in userid_ls:
            if i == key:
                innerid.append(elem)
    return innerid

In [ ]:
# labeling된 유저들의 지역별 inner_id

gw_innerid = user_to_inner(all_id_dic, gw_userid)
cc_innerid = user_to_inner(all_id_dic, cc_userid)
jl_innerid = user_to_inner(all_id_dic, jl_userid)
sd_innerid = user_to_inner(all_id_dic, sd_userid)
gs_innerid = user_to_inner(all_id_dic, gs_userid)

In [ ]:
print(len(gw_innerid), len(cc_innerid), len(jl_innerid), len(sd_innerid), len(gs_innerid))

224 319 129 1281 836

In [ ]:
print(cc_innerid)

[1072315070, 1548880302, 3867970394, 3980500203, 5746701289, 6106430649, 2797872, 2648672, 580170525, 589055421, 682724106, 675222645, 709698255, 693360949, 878381905, 868477720, 973608805, 981031685, 1000813867, 1005686920, 1047232420, 1197960592, 1230301628, 1267124617, 1289431827, 1305781000, 1315091477, 1315378327, 1338503512, 1365406687, 1366808488, 1368185338, 1370797659, 1371342892, 1377073670, 1394411224, 1393505677, 1404903386, 1405031871, 1412677029, 1415072429, 1419283002, 1444514852, 1453676043, 1455221375, 1461589515, 1467748785, 1469146271, 1473620124, 1477950971, 1488364408, 1510813266, 1531216639, 1536091013, 1542781229, 1553812285, 1561977495, 1563533063, 1580901088, 1587665278, 1588404478, 1593009590, 1605661332, 1606650556, 1620550322, 1640911992, 1641250170, 1650630930, 1697724497, 1717742858, 1779220135, 1793034911, 1795870459, 1805367461, 1806650109, 1817097312, 1903357392, 1912709228, 1922968878, 1930218320, 1944264179, 1952889380, 1950651269, 1978758263, 1980448384, 2016429490, 2060134033, 2063894854, 2076860985, 2076135944, 2089783883, 2124986995, 2128540647, 2152866451, 2148734541, 2212502886, 2210979280, 2228893697, 2239170707, 2242060221, 2253509385, 2257582695, 2272510975, 2278767928, 2280392499, 2302152131, 2321966022, 2592111299, 2659214109, 2712505101, 2714923820, 2760986797, 2778298745, 2897725290, 2962864025, 2981126916, 3035444217, 3048083105, 3050832518, 3095264697, 3157285287, 3177540279, 3179157487, 3182153299, 3217822119, 3222407067, 3243921221, 3257552653, 3270695208, 3299611652, 3434713385, 3434130972, 3494871562, 3584855771, 3604313574, 3609063422, 3606218224, 3862805050, 3881004183, 3901226536, 3895184513, 3959363853, 4054997077, 4089078149, 4103148542, 4129474810, 4135329491, 4141092014, 4140640327, 4173363619, 4194491240, 4199031230, 4200139897, 4212622715, 4226309411, 4402264048, 4434767475, 4473793895, 4477710855, 4662266239, 4733037181, 4790950547, 4845386054, 4862788825, 5001474891, 5394354874, 5437720625, 5493461991, 5498937977, 5543263135, 5564126072, 5586530554, 5599111805, 5638902335, 5644690522, 5690192421, 5757156026, 5870162586, 5920323050, 5994548730, 6044826646, 6129672906, 6171714790, 6403115647, 6437257530, 6692448082, 6709805288, 6892262501, 6932952887, 6951458617, 7054764114, 7092956379, 7126960276, 7188526581, 7276165263, 7315073291, 7393490028, 7389361667, 7444585470, 7465136891, 7571074608, 8009986997, 8098710004, 8159590854, 8200282030, 8275164818, 8330210764, 8458490192, 12312411522, 12886601210, 13204552196, 13378873991, 13389503988, 13479715524, 13580068590, 13709187530, 13811900068, 14474813248, 15180060177, 15361031813, 15409105072, 16657490419, 17315711171, 17941283048, 20735201682, 21296128014, 21967049894, 22362813671, 22942103341, 24423929113, 24720040002, 25028238631, 25441161710, 25852837576, 26067570917, 26434055623, 26950322048, 28082448353, 28396739634, 28840476010, 29097838767, 29149687252, 29849006530, 29936667219, 30113582631, 30097521193, 31755674262, 32028419000, 32737010850, 34008275468, 35110764922, 38469800679, 39205582436, 39718579061, 39901859586, 1953536014, 2033000437, 2052423720, 5351029572, 7464681607, 8167096006, 908436657, 908436657, 1197756741, 1197756741, 1398721051, 1398721051, 4852731028, 4852731028, 4852731028, 7300174770, 7300174770, 27691121173, 27691121173, 32343653903, 32343653903, 39506576439, 39506576439, 4461388, 990654681, 1306894832, 1432611447, 1456479267, 1474688676, 1483884991, 1529014635, 1629319345, 1673659326, 1700436846, 2096944558, 2937375679, 3079477735, 3222032831, 3520863986, 3894397879, 3912709704, 4024247727, 4273978889, 4305500161, 5358906842, 5534213178, 5647920289, 6090112518, 6863978160, 6909755069, 7510850384, 7721244146, 7722117787, 7941258704, 8497747209, 9377907005, 16648331541, 18826787373, 26053423536, 26665625090, 29602374121, 34408468403, 35621023181, 36586569142]

### 각 지역별 center user로부터 수집한 팔로워/팔로잉 id목록에서 labeling된 id만 남기기
- 예시 . 충청

In [ ]:
cc_df = pd.read_csv("/content/gdrive/My Drive/인스타그램_프로파일링/Relation(start, end)/cc_2.csv")

In [ ]:
cc_df

             start          end
0      13580068590  27733156208
1      13337514500  27733156208
2      27961899505  27733156208
3       5772973535  27733156208
4      27733156208  13580068590
...            ...          ...
10530   3188424467   5557754898
10531   3188424467   5763414441
10532   3188424467  31450672398
10533   3188424467   3685838615
10534   3188424467   1435555268

[10535 rows x 2 columns]

In [ ]:
cc_start = list(cc_df['start'])

In [ ]:
len(cc_start)

10535

In [ ]:
cc_start_ls = []
for v in cc_start:
    for j in cc_innerid:
        if v == j:
            cc_start_ls.append(v)

In [ ]:
cc_start_ls

[13580068590,
 13580068590,
 2592111299,
 13580068590,
 2592111299,
 4054997077,
 13580068590,
 13580068590,
 2280392499,
 30097521193,
 24720040002,
 13580068590,
 7276165263,
 7389361667,
 5599111805,
 13580068590,
 13580068590,
 35110764922,
 3494871562,
 29849006530,
 29149687252,
 1305781000,
 13580068590,
 26950322048,
 25028238631,
 3182153299,
 28840476010,
 8009986997,
 1930218320,
 8330210764,
 6437257530,
 5437720625,
 2981126916,
 39718579061,
 25441161710,
 6692448082,
 4194491240,
 3609063422,
 38469800679,
 3217822119,
 15180060177,
 7315073291,
 1542781229,
 3862805050,
 2778298745,
 13580068590,
 13580068590,
 1477950971,
 13580068590,
 39205582436,
 1806650109,
 1531216639,
 5543263135,
 13580068590,
 8098710004,
 3048083105,
 2962864025,
 1640911992,
 1912709228,
 1368185338,
 1795870459,
 4212622715,
 5757156026,
 4199031230,
 7571074608,
 5599111805,
 7389361667,
 1980448384,
 13580068590,
 13204552196,
 21296128014,
 3243921221,
 13580068590,
 5394354874,
 1315378327,
 13580068590,
 13580068590,
 13580068590,
 5564126072,
 13580068590,
 4473793895,
 5644690522,
 1405031871,
 1467748785,
 3050832518,
 682724106,
 13580068590,
 13378873991,
 13580068590,
 13580068590,
 13580068590,
 32737010850,
 8159590854,
 39901859586,
 4089078149,
 1952889380,
 1377073670,
 3177540279,
 1978758263,
 6129672906,
 29097838767,
 30113582631,
 3901226536,
 13580068590,
 13580068590,
 13479715524,
 1488364408,
 3035444217,
 3434130972,
 1605661332,
 13811900068,
 13709187530,
 2592111299,
 1697724497,
 13580068590,
 13580068590,
 13580068590,
 13580068590,
 3434713385,
 2302152131,
 13580068590,
 17941283048,
 5493461991,
 1641250170,
 3299611652,
 13580068590,
 2076135944,
 13580068590,
 3584855771,
 13580068590,
 13580068590,
 4173363619,
 1641250170,
 3584855771,
 13580068590,
 2076860985,
 7389361667,
 6403115647,
 1641250170,
 1606650556,
 3299611652,
 1980448384,
 13580068590,
 2253509385,
 2148734541,
 13580068590,
 2212502886,
 2257582695,
 7092956379,
 13580068590,
 34008275468,
 31755674262,
 15361031813,
 4790950547,
 13580068590,
 13580068590,
 4434767475,
 1510813266,
 28396739634,
 1980448384,
 675222645,
 580170525,
 2152866451,
 7389361667,
 5599111805,
 22362813671,
 13580068590,
 6171714790,
 12312411522,
 2124986995,
 1371342892,
 2228893697,
 2242060221,
 3270695208,
 8200282030,
 1305781000,
 2712505101,
 3179157487,
 3895184513,
 1903357392,
 3157285287,
 1455221375,
 4103148542,
 4402264048,
 8275164818,
 589055421,
 2278767928,
 21967049894,
 1587665278,
 4140640327,
 709698255,
 28082448353]

In [ ]:
len(cc_start_ls)

192

In [ ]:
cc_start_uni = pd.unique(cc_start_ls)
print(cc_start_uni)
print(len(cc_start_uni))

[13580068590  2592111299  4054997077  2280392499 30097521193 24720040002
  7276165263  7389361667  5599111805 35110764922  3494871562 29849006530
 29149687252  1305781000 26950322048 25028238631  3182153299 28840476010
  8009986997  1930218320  8330210764  6437257530  5437720625  2981126916
 39718579061 25441161710  6692448082  4194491240  3609063422 38469800679
  3217822119 15180060177  7315073291  1542781229  3862805050  2778298745
  1477950971 39205582436  1806650109  1531216639  5543263135  8098710004
  3048083105  2962864025  1640911992  1912709228  1368185338  1795870459
  4212622715  5757156026  4199031230  7571074608  1980448384 13204552196
 21296128014  3243921221  5394354874  1315378327  5564126072  4473793895
  5644690522  1405031871  1467748785  3050832518   682724106 13378873991
 32737010850  8159590854 39901859586  4089078149  1952889380  1377073670
  3177540279  1978758263  6129672906 29097838767 30113582631  3901226536
 13479715524  1488364408  3035444217  3434130972  1605661332 13811900068
 13709187530  1697724497  3434713385  2302152131 17941283048  5493461991
  1641250170  3299611652  2076135944  3584855771  4173363619  2076860985
  6403115647  1606650556  2253509385  2148734541  2212502886  2257582695
  7092956379 34008275468 31755674262 15361031813  4790950547  4434767475
  1510813266 28396739634   675222645   580170525  2152866451 22362813671
  6171714790 12312411522  2124986995  1371342892  2228893697  2242060221
  3270695208  8200282030  2712505101  3179157487  3895184513  1903357392
  3157285287  1455221375  4103148542  4402264048  8275164818   589055421
  2278767928 21967049894  1587665278  4140640327   709698255 28082448353]
138

In [ ]:
cc_end = list(cc_df['end'])
cc_end

[27733156208,
 27733156208,
 27733156208,
 27733156208,
 13580068590,
 37826567075,
 40384414061,
 40817735077,
 37826567075,
 4458875249,
 37826567075,
 37826567075,
 40384414061,
 15953310530,
 13337514500,
 37826567075,
 37826567075,
 40384414061,
 40384414061,
 40384414061,
 25941073319,
 27961899505,
 37826567075,
 37826567075,
 40384414061,
 40384414061,
 40384414061,
 13580068590,
 5772973535,
 37826567075,
 37826567075,
 40384414061,
 40384414061,
 10714671034,
 37826567075,
 37826567075,
 40384414061,
 40384414061,
 40384414061,
 37826567075,
 3180255400,
 37826567075,
 37826567075,
 2592111299,
 40384414061,
 7546113177,
 9198333447,
 7235829698,
 13580068590,
 13580068590,
 5634736653,
 7479640251,
 3608161032,
 37826567075,
 7546113177,
 4054997077,
 2983112233,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 31075843149,
 6765985832,
 8441060449,
 33216337376,
 5072776356,
 5373998226,
 33216337376,
 9734464248,
 8216962805,
 3531131353,
 21192399555,
 5453444990,
 13233617374,
 2264203813,
 38321404742,
 37826567075,
 2642297336,
 3224306906,
 2953663692,
 7005883919,
 4694876391,
 13632896816,
 35309955163,
 4205289489,
 38413588742,
 3088673296,
 9409592050,
 1303329532,
 3706920980,
 8708915681,
 6059444984,
 13580068590,
 4960449121,
 3545309074,
 4378667757,
 8470073440,
 6041854569,
 334278857,
 3621970819,
 22103820662,
 1446929037,
 5359053193,
 13580068590,
 24726605646,
 372603223,
 1723017725,
 2909685764,
 5864070920,
 24726605646,
 24726605646,
 1360855002,
 781462702,
 1127312106,
 7172929958,
 7794995507,
 13378636381,
 15554174007,
 24726605646,
 24726605646,
 4176556104,
 6485920149,
 4810735059,
 9057548671,
 15554174007,
 24726605646,
 24726605646,
 1179822620,
 7090024262,
 5655410199,
 6173268891,
 1591561896,
 2680328413,
 15554174007,
 6290971355,
 24726605646,
 24726605646,
 5551037438,
 606511721,
 3586065713,
 19132307989,
 2113226221,
 8308505066,
 15554174007,
 6290971355,
 6290971355,
 24726605646,
 24726605646,
 6251344260,
 1121842136,
 4226685742,
 3302785705,
 15554174007,
 6290971355,
 24726605646,
 24726605646,
 6837775869,
 3242109212,
 8255530255,
 6290971355,
 24726605646,
 24726605646,
 3690623989,
 4211071711,
 4223312685,
 7105044936,
 1636234331,
 6290971355,
 6290971355,
 24726605646,
 24726605646,
 1271296792,
 1461589515,
 14294684215,
 15519061409,
 6290971355,
 6290971355,
 24726605646,
 24726605646,
 1021296758,
 7003091110,
 2234643630,
 4226521457,
 13622163976,
 4499469343,
 15651815953,
 6290971355,
 24726605646,
 24726605646,
 1089868848,
 17286225876,
 1483413108,
 2326257705,
 12803183954,
 6290971355,
 6290971355,
 6290971355,
 6290971355,
 24726605646,
 24726605646,
 35537262082,
 11446099162,
 10566767072,
 6123297776,
 6290971355,
 24726605646,
 24726605646,
 6937567323,
 4088592596,
 8770599828,
 6290971355,
 6290971355,
 6290971355,
 24726605646,
 24726605646,
 34421654132,
 11650969494,
 3602832237,
 6290971355,
 24726605646,
 24726605646,
 34916055596,
 871731054,
 4216281463,
 2349443399,
 13580068590,
 6290971355,
 24726605646,
 24726605646,
 9289720003,
 3898374335,
 1449549278,
 19059895760,
 15907834293,
 6290971355,
 6290971355,
 24726605646,
 24726605646,
 7787681998,
 19148974507,
 6979730365,
 13581103519,
 1454142084,
 6290971355,
 1365377883,
 9200230377,
 8016904707,
 18601034594,
 3561087126,
 1247627659,
 2908564985,
 537708018,
 6290971355,
 6290971355,
 6290971355,
 23895862386,
 13580068590,
 30252430863,
 4336687737,
 3662673309,
 6971565399,
 1636281262,
 6290971355,
 8634667664,
 12764113225,
 3964163036,
 3029255251,
 1619869665,
 1524991350,
 11179792282,
 10229457243,
 6290971355,
 2091578667,
 1269263207,
 21590063845,
 6290971355,
 6290971355,
 8171364702,
 20401987159,
 3177640700,
 1653231723,
 1127175046,
 4044579465,
 6290971355,
 6290971355,
 6290971355,
 6290971355,
 20060547189,
 13838648302,
 26449835696,
 5037484494,
 6290971355,
 6290971355,
 6290971355,
 6290971355,
 8967861171,
 10726076074,
 1492711388,
 4251536348,
 1921871617,
 4568273689,
 6682385272,
 10158384860,
 6061210504,
 6290971355,
 1946890186,
 1519741795,
 2002607245,
 13466272261,
 27038061707,
 6290971355,
 23994220,
 24540129737,
 17785189146,
 6146157410,
 468789687,
 2036256424,
 27648597152,
 3426866023,
 6290971355,
 12653026276,
 12731449978,
 1375686681,
 24488114502,
 8516893516,
 1400237376,
 8094904895,
 3552385622,
 6290971355,
 6290971355,
 6290971355,
 12653026276,
 12731449978,
 12731449978,
 12731449978,
 20583669698,
 18735109642,
 175694806,
 26079646587,
 6394189381,
 1633190465,
 17090670950,
 15664528328,
 5705242103,
 6290971355,
 12653026276,
 3520966597,
 12731449978,
 6847854228,
 2036491737,
 268242356,
 6987726022,
 32181119482,
 6290971355,
 13580068590,
 12731449978,
 6847854228,
 1710101677,
 1966209948,
 6233407021,
 6290971355,
 9681937631,
 12731449978,
 6847854228,
 2373786295,
 5384997696,
 1526847967,
 1423476873,
 5715953339,
 5504270505,
 17768203882,
 1476896117,
 1139617015,
 7904827106,
 8141983556,
 8590975993,
 1481095245,
 31946667886,
 1981156106,
 1798946142,
 1982578027,
 33389607024,
 1562450580,
 6290971355,
 6290971355,
 2225202753,
 1775688662,
 7964987666,
 11842434715,
 11933628279,
 12731449978,
 12731449978,
 12731449978,
 12731449978,
 12731449978,
 12731449978,
 8657928918,
 5599111805,
 3917675105,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 1733723871,
 212742998,
 10353762371,
 2028847247,
 4480562868,
 6925486138,
 8386418225,
 521663931,
 4169565990,
 294613467,
 1400185233,
 6600651059,
 7679693186,
 6503211720,
 27490912512,
 33637762847,
 1121717927,
 1288225270,
 10387814197,
 6008320517,
 2870668709,
 11652196932,
 17768323797,
 1222039976,
 3594285522,
 3429830741,
 2274763833,
 8717991311,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6762364620,
 719848330,
 2357006857,
 703520458,
 5786347817,
 10425294356,
 7908190152,
 1496127491,
 32753872187,
 31611695812,
 5666654362,
 9010765410,
 6436190813,
 3265382557,
 13580068590,
 2376453936,
 7105105657,
 4744291824,
 1981120373,
 8320874434,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6327949755,
 14015330998,
 14475392871,
 419979862,
 3922204442,
 2298035931,
 8011506095,
 8004108750,
 6682364637,
 31394702790,
 4951476988,
 4024075850,
 1520109215,
 6766867501,
 4766868491,
 7093852363,
 28446482093,
 13348015625,
 7213554272,
 1394411224,
 2167317797,
 1979552504,
 13472458854,
 4662266239,
 1510883818,
 3598553901,
 1489964788,
 721241777,
 3570727021,
 2110975046,
 1464055110,
 3965545823,
 2459168130,
 4179158077,
 2949593175,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 491862741,
 347146908,
 1633681945,
 1558142054,
 6749828450,
 32733958430,
 12875521909,
 5567468662,
 8431231830,
 13580068590,
 6889859009,
 7230443500,
 4624412209,
 5523072466,
 7952611953,
 6909850788,
 4117897491,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 2107411892,
 1122852601,
 8012033210,
 2274763833,
 582247876,
 636206887,
 4583191966,
 4224843546,
 3204875694,
 6696776391,
 4070428919,
 19633110702,
 5993989926,
 10877055697,
 8624859349,
 16472048372,
 5802351032,
 7692970880,
 7317800591,
 6979554407,
 6338255129,
 1991675724,
 1725613803,
 2227830284,
 4473943506,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 246194371,
 2263846028,
 29728565,
 19615686,
 4063385254,
 104906612,
 1072060036,
 766303860,
 8025277114,
 7033581038,
 6709805288,
 2937513246,
 8387461504,
 6983325909,
 1482071521,
 1577716280,
 6317971120,
 1913409301,
 2267679429,
 2963450259,
 3299489399,
 4730227548,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 26669533,
 178537482,
 10426737102,
 1483225497,
 4943342061,
 3102740515,
 31146164286,
 3476721263,
 5446597141,
 3273973683,
 3101957940,
 4719051233,
 3056569788,
 3913844460,
 4003998255,
 29107215319,
 6847854228,
 6847854228,
 1270839365,
 12281817,
 1927805140,
 591745860,
 650953699,
 1414222546,
 1314890247,
 260375673,
 6380930,
 8635791893,
 18089728946,
 6994848777,
 6868038938,
 1684702875,
 2909690996,
 4101936887,
 4351190490,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 32912684884,
 18428658,
 7719696,
 259925762,
 3132929984,
 145821237,
 3420133378,
 33411994815,
 3235330581,
 2231277877,
 2188940412,
 1943293995,
 1529703489,
 5679206892,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6847854228,
 6847854228,
 6847854228,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 19410587,
 6590609,
 18918467,
 8586584,
 208560325,
 427553890,
 247944034,
 3449942815,
 3552449457,
 3313291392,
 2885364287,
 2325005604,
 2280392499,
 1705958521,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 32912684884,
 32912684884,
 2095060625,
 232192182,
 5020663420,
 13460080,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 1724438788,
 3565989397,
 1126358805,
 189393625,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 5949107467,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6847854228,
 6847854228,
 6847854228,
 6847854228,
 7087462088,
 3611637412,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 9958036300,
 9361591635,
 1946373972,
 2727996945,
 5949107467,
 5949107467,
 33440022477,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 8312033165,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 33440022477,
 33440022477,
 33440022477,
 33440022477,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 7048946038,
 14513652954,
 4964534103,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 33440022477,
 33440022477,
 33440022477,
 33440022477,
 33440022477,
 6681535961,
 6349631582,
 22987306006,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 6323519178,
 10636921683,
 13355504400,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 33440022477,
 33440022477,
 33440022477,
 33440022477,
 6681535961,
 6681535961,
 6681535961,
 6681535961,
 6681535961,
 6681535961,
 6681535961,
 6681535961,
 6681535961,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 1771655914,
 1533901674,
 8286993139,
 32430438180,
 12263707817,
 5949107467,
 5949107467,
 33440022477,
 33440022477,
 6681535961,
 6681535961,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 35411463134,
 36363803102,
 27263283700,
 4345679021,
 5602396655,
 2279969232,
 5461545394,
 4512491721,
 5981770876,
 6818061441,
 5949107467,
 5949107467,
 5949107467,
 5949107467,
 33440022477,
 33440022477,
 33440022477,
 6681535961,
 6681535961,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 6349631582,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 22987306006,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 32912684884,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 29107215319,
 13037075747,
 5877314874,
 28237619942,
 5342219106,
 15518858567,
 1407217915,
 ...]

In [ ]:
cc_end_ls = []
for w in cc_end:
    for q in cc_innerid:
        if w == q:
            cc_end_ls.append(w)
cc_end_ls

[13580068590,
 13580068590,
 2592111299,
 13580068590,
 13580068590,
 4054997077,
 13580068590,
 13580068590,
 1461589515,
 13580068590,
 13580068590,
 13580068590,
 5599111805,
 13580068590,
 1394411224,
 4662266239,
 13580068590,
 6709805288,
 2280392499,
 1536091013,
 13580068590,
 13580068590,
 5001474891,
 26434055623,
 4226309411,
 4733037181,
 1197960592,
 13580068590,
 1593009590,
 6044826646,
 1047232420,
 1488364408,
 3222407067,
 28082448353,
 7126960276,
 1553812285,
 4200139897,
 29936667219,
 2797872,
 1365406687,
 973608805,
 26067570917,
 13580068590,
 26950322048,
 3182153299,
 1561977495,
 13389503988,
 8330210764,
 2659214109,
 4135329491,
 5498937977,
 13580068590,
 8009986997,
 2063894854,
 24423929113,
 878381905,
 4129474810,
 6692448082,
 13580068590,
 6932952887,
 2648672,
 1412677029,
 14474813248,
 13580068590,
 20735201682,
 2060134033,
 25441161710,
 22942103341,
 5437720625,
 1922968878,
 2016429490,
 1453676043,
 1267124617,
 17315711171,
 4141092014,
 13580068590,
 2321966022,
 7315073291,
 1542781229,
 1393505677,
 5870162586,
 13580068590,
 868477720,
 15409105072,
 7188526581,
 7393490028,
 3257552653,
 13580068590,
 4194491240,
 2239170707,
 1563533063,
 1620550322,
 7465136891,
 2272510975,
 38469800679,
 16657490419,
 8458490192,
 6951458617,
 1469146271,
 5543263135,
 1806650109,
 1338503512,
 1531216639,
 7571074608,
 13580068590,
 8098710004,
 5599111805,
 7389361667,
 3048083105,
 5757156026,
 1980448384,
 2962864025,
 1477950971,
 13580068590,
 1640911992,
 1912709228,
 4212622715,
 1795870459,
 13204552196,
 13580068590,
 21296128014,
 13580068590,
 3243921221,
 5394354874,
 13580068590,
 13580068590,
 981031685,
 13580068590,
 13580068590,
 13580068590,
 13580068590,
 13580068590,
 13580068590,
 1580901088,
 32737010850,
 8159590854,
 39901859586,
 4089078149,
 1377073670,
 13580068590,
 30113582631,
 13580068590,
 13479715524,
 2592111299,
 7444585470,
 1488364408,
 13811900068,
 13709187530,
 3881004183,
 2760986797,
 13580068590,
 6892262501,
 13580068590,
 2897725290,
 3299611652,
 1000813867,
 13580068590,
 13580068590,
 13580068590,
 5493461991,
 12886601210,
 4845386054,
 13580068590,
 1641250170,
 13580068590,
 3299611652,
 2076135944,
 13580068590,
 1415072429,
 1793034911,
 2148734541,
 3584855771,
 13580068590,
 7389361667,
 2076860985,
 3584855771,
 1980448384,
 5994548730,
 1779220135,
 6403115647,
 1473620124,
 5690192421,
 1641250170,
 3299611652,
 13580068590,
 1641250170,
 7092956379,
 1606650556,
 5638902335,
 1650630930,
 13580068590,
 13580068590,
 1588404478,
 3959363853,
 1817097312,
 1366808488,
 3606218224,
 1371342892,
 2210979280,
 5586530554,
 2124986995,
 1717742858,
 1289431827,
 1980448384,
 1315091477,
 12312411522,
 1305781000,
 3270695208,
 3604313574,
 2712505101,
 2714923820,
 1444514852,
 3895184513,
 1404903386,
 1005686920,
 3179157487,
 24423929113,
 5599111805,
 693360949,
 3095264697,
 25852837576,
 4862788825,
 2089783883,
 1419283002,
 4477710855,
 5920323050,
 13580068590,
 3157285287,
 1903357392,
 7389361667,
 1944264179,
 1455221375,
 28082448353,
 4103148542,
 32028419000,
 1230301628,
 1805367461,
 2128540647,
 1950651269,
 4402264048,
 1370797659,
 7054764114]

In [ ]:
len(cc_end_ls)

242

In [ ]:
cc_end_uni = pd.unique(cc_end_ls)
print(cc_end_uni)
print(len(cc_end_uni))

[13580068590  2592111299  4054997077  1461589515  5599111805  1394411224
  4662266239  6709805288  2280392499  1536091013  5001474891 26434055623
  4226309411  4733037181  1197960592  1593009590  6044826646  1047232420
  1488364408  3222407067 28082448353  7126960276  1553812285  4200139897
 29936667219     2797872  1365406687   973608805 26067570917 26950322048
  3182153299  1561977495 13389503988  8330210764  2659214109  4135329491
  5498937977  8009986997  2063894854 24423929113   878381905  4129474810
  6692448082  6932952887     2648672  1412677029 14474813248 20735201682
  2060134033 25441161710 22942103341  5437720625  1922968878  2016429490
  1453676043  1267124617 17315711171  4141092014  2321966022  7315073291
  1542781229  1393505677  5870162586   868477720 15409105072  7188526581
  7393490028  3257552653  4194491240  2239170707  1563533063  1620550322
  7465136891  2272510975 38469800679 16657490419  8458490192  6951458617
  1469146271  5543263135  1806650109  1338503512  1531216639  7571074608
  8098710004  7389361667  3048083105  5757156026  1980448384  2962864025
  1477950971  1640911992  1912709228  4212622715  1795870459 13204552196
 21296128014  3243921221  5394354874   981031685  1580901088 32737010850
  8159590854 39901859586  4089078149  1377073670 30113582631 13479715524
  7444585470 13811900068 13709187530  3881004183  2760986797  6892262501
  2897725290  3299611652  1000813867  5493461991 12886601210  4845386054
  1641250170  2076135944  1415072429  1793034911  2148734541  3584855771
  2076860985  5994548730  1779220135  6403115647  1473620124  5690192421
  7092956379  1606650556  5638902335  1650630930  1588404478  3959363853
  1817097312  1366808488  3606218224  1371342892  2210979280  5586530554
  2124986995  1717742858  1289431827  1315091477 12312411522  1305781000
  3270695208  3604313574  2712505101  2714923820  1444514852  3895184513
  1404903386  1005686920  3179157487   693360949  3095264697 25852837576
  4862788825  2089783883  1419283002  4477710855  5920323050  3157285287
  1903357392  1944264179  1455221375  4103148542 32028419000  1230301628
  1805367461  2128540647  1950651269  4402264048  1370797659  7054764114]
180

In [ ]:
# 그냥 확인차원에서 다시 뽑아본거
cc_df

             start          end
0      13580068590  27733156208
1      13337514500  27733156208
2      27961899505  27733156208
3       5772973535  27733156208
4      27733156208  13580068590
...            ...          ...
10530   3188424467   5557754898
10531   3188424467   5763414441
10532   3188424467  31450672398
10533   3188424467   3685838615
10534   3188424467   1435555268

[10535 rows x 2 columns]

In [ ]:
# NAN값을 포함한 re_end라는 컬럼 하나 만들고
cc_df['re_end'] = np.nan

In [ ]:
cc_df

             start          end  re_end
0      13580068590  27733156208     NaN
1      13337514500  27733156208     NaN
2      27961899505  27733156208     NaN
3       5772973535  27733156208     NaN
4      27733156208  13580068590     NaN
...            ...          ...     ...
10530   3188424467   5557754898     NaN
10531   3188424467   5763414441     NaN
10532   3188424467  31450672398     NaN
10533   3188424467   3685838615     NaN
10534   3188424467   1435555268     NaN

[10535 rows x 3 columns]

In [ ]:
# 라벨링된 inner_id가 end에 포함되면 1을 부여함
for i, v in enumerate(cc_df['end']):
    for j in cc_end_uni:
        if v == j:
            cc_df.loc[i, ['re_end']] = 1

In [ ]:
cc_df

             start          end  re_end
0      13580068590  27733156208     NaN
1      13337514500  27733156208     NaN
2      27961899505  27733156208     NaN
3       5772973535  27733156208     NaN
4      27733156208  13580068590     1.0
...            ...          ...     ...
10530   3188424467   5557754898     NaN
10531   3188424467   5763414441     NaN
10532   3188424467  31450672398     NaN
10533   3188424467   3685838615     NaN
10534   3188424467   1435555268     NaN

[10535 rows x 3 columns]

In [ ]:
# 1이 없는 NaN값이 있으면 일괄적으로 행 삭제
cc_df_a = cc_df.dropna(how="any")

In [ ]:
# 결과
cc_df_a

             start          end  re_end
4      27733156208  13580068590     1.0
27     40817735077  13580068590     1.0
43     40384414061   2592111299     1.0
48     37826567075  13580068590     1.0
49     40384414061  13580068590     1.0
...            ...          ...     ...
10474  21288013297   2128540647     1.0
10484  21288013297   1950651269     1.0
10485  21288013297   4402264048     1.0
10486  21288013297   1370797659     1.0
10528   3188424467   7054764114     1.0

[242 rows x 3 columns]

In [ ]:
# re_end 칼럼 삭제하면 최종 start, end 값만 남음
cc_df_b = cc_df_a.drop(columns=["re_end"])

In [ ]:
cc_df_b

             start          end
4      27733156208  13580068590
27     40817735077  13580068590
43     40384414061   2592111299
48     37826567075  13580068590
49     40384414061  13580068590
...            ...          ...
10474  21288013297   2128540647
10484  21288013297   1950651269
10485  21288013297   4402264048
10486  21288013297   1370797659
10528   3188424467   7054764114

[242 rows x 2 columns]

In [ ]:
# 결과 저장
cc_df_b.to_csv("/content/gdrive/My Drive/프로젝트/cc_ex/re_cc_2.csv")