<a href="https://colab.research.google.com/github/Sjing2/SJ_practice/blob/master/crawl_test_1/crawl_test_1/spiders/6_delete_follower1000_like1000_%EC%BD%94%EB%93%9C%EC%88%98%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive/

In [2]:
import re
import pandas as pd
import os

In [3]:
os.chdir('/content/gdrive/My Drive/인스타그램_프로파일링/Post')
new_df = pd.read_csv('cc_hangul.csv')

In [4]:
new_df

         shortcode  ...                                          next_page
0      CEasJz1JPgQ  ...  https://www.instagram.com/graphql/query/?query...
1      CEY3iR2pr-l  ...  https://www.instagram.com/graphql/query/?query...
2      CEYOgJUJ1KR  ...  https://www.instagram.com/graphql/query/?query...
3      CEWyKvgJE1C  ...  https://www.instagram.com/graphql/query/?query...
4      CEWde7hJDk1  ...  https://www.instagram.com/graphql/query/?query...
...            ...  ...                                                ...
36680  CDd8XJ4Fm3Y  ...  https://www.instagram.com/graphql/query/?query...
36681  CDd7qDAlaO3  ...  https://www.instagram.com/graphql/query/?query...
36682  CDd7U1IFXCu  ...  https://www.instagram.com/graphql/query/?query...
36683  CDd60iUlSIr  ...  https://www.instagram.com/graphql/query/?query...
36684  CDdjlfqlZEf  ...  https://www.instagram.com/graphql/query/?query...

[36685 rows x 14 columns]

In [5]:
over1000_df = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Relation(start, end)/cc_over1000.csv')

In [6]:
over1000_df

    Unnamed: 0         data
0            0  23898132889
1            1   7159109885
2            2   7798342681
3            3  38063234978
4            4   3043715720
5            5   2525851289
6            6  31785307735
7            7   6813567329
8            8  13317184033
9            9   7459407725
10          10  12868701287
11          11  21729607473

In [7]:
def del_over1000(df, over1000_df):
    # 팔로워 1000명 이상 id 제외
    for over1000_id in list(over1000_df['data']):
        idx = df[df['inner_id']==str(over1000_id)].index
        df.drop(idx, inplace=True)
        
    id_lst = list(set(df['insta_id']))
    print(len(id_lst))
        
    # 좋아요 1000개 이상 게시물 있는 id 제외
    df['like_count'] = df['like_count'].apply(int)
    id_lst = list(set(df['insta_id']))
    for user_id in id_lst:
        count = 0
        for y in list(df[df['insta_id']==user_id]['like_count']):
            if y > 1000:
                count += 1
        if count >= 1:
            idx = df[df['insta_id']==user_id].index
            df.drop(idx, inplace=True)
    id_lst = list(set(df['insta_id']))
    print(len(id_lst))
    return df

In [8]:
new_new_df = del_over1000(new_df, over1000_df)

/usr/local/lib/python3.6/dist-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

1726
1561

In [9]:
new_new_df

         shortcode  ...                                          next_page
0      CEasJz1JPgQ  ...  https://www.instagram.com/graphql/query/?query...
1      CEY3iR2pr-l  ...  https://www.instagram.com/graphql/query/?query...
2      CEYOgJUJ1KR  ...  https://www.instagram.com/graphql/query/?query...
3      CEWyKvgJE1C  ...  https://www.instagram.com/graphql/query/?query...
4      CEWde7hJDk1  ...  https://www.instagram.com/graphql/query/?query...
...            ...  ...                                                ...
36680  CDd8XJ4Fm3Y  ...  https://www.instagram.com/graphql/query/?query...
36681  CDd7qDAlaO3  ...  https://www.instagram.com/graphql/query/?query...
36682  CDd7U1IFXCu  ...  https://www.instagram.com/graphql/query/?query...
36683  CDd60iUlSIr  ...  https://www.instagram.com/graphql/query/?query...
36684  CDdjlfqlZEf  ...  https://www.instagram.com/graphql/query/?query...

[32830 rows x 14 columns]

In [10]:
id_lst = list(set(new_new_df['insta_id']))
len(id_lst)

1561

In [11]:
new_df.to_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/cc_delete.csv', index=False)